services:
  claude-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-dev
    volumes:
      - ".:/workspace:cached"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GIT_USER_NAME=${GIT_USER_NAME:-}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - AUTO_START_CLAUDE=${AUTO_START_CLAUDE:-false}
    ports:
      - "3000:3000"
      - "8000:8000"
      - "8080:8080"
      - "9000:9000"
      - "5000:5000"
      - "4200:4200"
      - "3001:3001"
      - "8888:8888"
      - "6006:6006"
    stdin_open: true
    tty: true