name: ShellCheck

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'
        severity: error
        
    - name: Check script permissions
      run: |
        # Ensure all scripts are executable
        find scripts -name "*.sh" -type f | while read script; do
          if [[ ! -x "$script" ]]; then
            echo "Error: $script is not executable"
            exit 1
          fi
        done